class Pin:
    IN: int
    OUT: int
    PULL_UP: int
    PULL_DOWN: int

    def __init__(self, id: int | str, mode: int = ..., pull: int | None = ...) -> None: ...
    def value(self, x: int | None = ...) -> int: ...
    def on(self) -> None: ...
    def off(self) -> None: ...


class I2C:
    def __init__(self, id: int, *, scl: Pin | None = ..., sda: Pin | None = ..., freq: int = ...) -> None: ...
    def scan(self) -> list[int]: ...


def reset() -> None: ...
