from typing import Protocol, runtime_checkable, Any, Optional, Callable

@runtime_checkable
class EventType(Protocol):
    callback: Callable[..., Any] 
    event: str
    args: dict[str, Any]
    events: Optional[dict[str, Callable[..., Any]]]

    def __init__(self,
                 callback: Callable[..., Any],
                 args: dict[str, Any],
                 event: str = "") -> None: ...
    def get_event_name(self) -> Optional[str]: ...
    def setup(self) -> None: ...
    def get_args(self) -> str: ...
    def to_rfw(self) -> str: ...

@runtime_checkable
class ContextNodeType(Protocol):
    _stack: list["ContextNodeType"]
    name: str
    kwargs: dict[str, Any]
    parent: Optional["ContextNodeType"]
    child_nodes: dict[str, list["ContextNodeType"]]
    _child_keyname: str
    multi_child: bool
    alias_name: Optional[str]
    _child_nodes: list["ContextNodeType"]

    def __init__(self, name: str, multi_child: bool, **kwargs: Any) -> None: ...
    def __enter__(self) -> "ContextNodeType": ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...
    def add_child(self, child: "ContextNodeType") -> "ContextNodeType": ...
    def remove_child(self, child: "ContextNodeType") -> "ContextNodeType": ...
    @classmethod
    def get_parent_node(cls) -> Optional["ContextNodeType"]: ...
    def __repr__(self) -> str: ...
    def print_tree(self, indent: int, print_args: bool) -> None: ...
    @property
    def children(self) -> list["ContextNodeType"]: ...
    @property
    def child(self) -> Optional["ContextNodeType"]: ...

@runtime_checkable
class WidgetType(Protocol):
    name: str
    args: dict[str, Any]
    page: Optional["PageType"]

    def __init__(self, name: str, multi_child: bool, **kwargs: Any) -> None: ...
    def setup(self) -> None: ...
    def setup_event(self, event: Optional[EventType]) -> None: ...
    def _setup_child(self, keyname: str, child: list[ContextNodeType]) -> None: ...
    def setup_child(self) -> None: ...
    def alias(self, name: str) -> "WidgetType": ...
    def to_rfw(self) -> str: ...

@runtime_checkable
class PageType(Protocol):
    packages: list[str]
    page: "PageType"
    events: dict[str, Callable[..., Any]]
    assets_directory: str

    def __init__(self, packages: list[str]) -> None: ...
    def setup_widgets(self) -> None: ...
    def get_packages(self) -> str: ...
    def get_widgets(self) -> str: ...
    def to_rfw(self) -> str: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...
