[project]
name = "pyrite-sdk"
version = "1.0.0"
description = "Expand your PyriteIDE"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "build>=1.4.3",
    "setuptools>=82.0.1",
    "pydantic>=2.13.4",
    "typer>=0.25.1",
    "rich>=13.0.0",
]
authors = [
    {name = "Can1425", email = "myqf1425@126.com"},
    {name = "kaixin1106", email = "kaixin168kx@163.com"},
]
keywords = ["pyrite", "PyriteIDE", "PyriteSDK", "MicroPython"]

[project.scripts]
pyrsdk = "tools.main:app"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
include = ["pyrite_sdk*", "tools*"]

[tool.setuptools.package-data]
"*" = ["*.py", "*.toml", "*.txt", "*.md", "*.pyi", "py.typed"]
