[general]
name = "English Language Pack"
id = "en-lang-pack"
version = "1.0.0"
python_version = "3.14"
author = "Pyrite Examples"
type = "data"

[permissions]
data = true

[platform]
linux = true
macos = true
windows = true
android = true
