[general]
name = "Template Ui Plugin"
id = "template-ui-plugin"
version = "1.0.0"
python_version = "3.14"
author = "Your name"
type = "ui"

[permissions]
ui = true

[platform]
linux = true
macos = true
windows = true
android = true
