from abc import ABC, abstractmethod
from ..interfaces.ui import PageType

class Plugin(ABC):
    pages: dict[str, PageType]

    def on_install(self): ...

    @abstractmethod
    def on_start(self): ...

    def on_pause(self): ...

    def on_resume(self): ...

    @abstractmethod
    def on_dispose(self): ...

    def on_uninstall(self): ...
