[general]
name = "Template Service Plugin"
id = "template-service-plugin"
version = "1.0.0"
python_version = "3.14"
author = "Your name"
type = "service"

[permissions]
file = true

[platform]
linux = true
macos = true
windows = true
android = true
